variable "name" {}
variable "key_name" {}
variable "aws_amis" {}
variable "aws_region" {}
variable "public_subnet_id_secondary" {}
variable "public_subnet_id_primary" {}
variable "alb_sg_id" {}
variable "web_sg_id" {}
variable "private_subnet_id" {}
variable "bastion_sg_id" {}
variable "vpc_id" {}
